language: python
python:
- '2.7'
env:
- TOXENV=docs
- TOXENV=py27
install:
- pip install tox
script: make test
deploy:
  provider: pypi
  user: yelplabs
  password:
    secure: TpSTlFu89tciZzboIfitHhU5NhAB1L1/rI35eQTXstiqzYg2mweOuip+MPNx9AlX3Swg7MhaFYnSUvRqPljuoLjLD0EQ7BHLVSBFl92ukkAMTeKvM6LbB9HnGOwzmAvTR5coegk8IHiegudODWvnhIj4hp7/0EA+gVX7E55kEAw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Yelp/elastalert
    branch: master
