apiVersion: v1
description: Automated rule-based alerting for Elasticsearch
name: elastalert2
version: 2.2.3
appVersion: 2.2.3
home: https://github.com/jertel/elastalert2
sources:
- https://github.com/jertel/elastalert2
maintainers:
  - name: jertel
engine: gotpl
