name: publish_image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    tags:
      - 2.*

env:
  IMAGE_NAME: elastalert2
  DOCKER_REPO: jertel/elastalert2

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Log into Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          # Push to GitHub Package
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          # Push to Docker Hub
          docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
          docker push $DOCKER_REPO:$VERSION

          if [[ "$VERSION" == "2."* ]]; then
            # Push to GitHub Package
            docker tag $IMAGE_NAME $IMAGE_ID:2
            docker push $IMAGE_ID:2

            # Push to Docker Hub
            docker tag $IMAGE_NAME $DOCKER_REPO:2
            docker push $DOCKER_REPO:2
          fi